notifications:
  email: false

sudo: false

language: rust

addons:
  apt:
    packages:
      - libasound2-dev

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: osx
      rust: stable

script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test --all --verbose
    